// cloud-run-one.script [script] [target]

script = args[0];

servers = getPurchasedServers();
for (i = 0; i < servers.length; i++) {
    server = servers[i];
    threads = 1;
    tprint("Running "+threads+"x "+script+" on "+server);
    if (threads > 0) {
        exec(script, server, threads);
        // exec(script, server, threads, args[1] ,args[2] ,args[3] ,args[4] ,args[5] ,args[6] ,args[7] ,args[8] ,args[9] ,args[10]);
    }
}