// remote-run.script [script] [hosts...]

script = args[0];

for (i = 1; i < args.length; i++) {
    host = args[i];
    
    scp(script, host);
    
    ram = getServerRam(host);
    freeRam = ram[0] - ram[1];
    threads = Math.floor(freeRam / getScriptRam(script, host));
    print("Running "+threads+"x "+script+" on "+host);
    if (threads >= 1) {
        exec(script, host, threads, host);
    }
}